### ISSUE TITLE
ValueError: Modules that have backward hooks assigned can't be compiled: Conv2d(512, 18, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))

### ISSUE THREAD

**Issue by Kurocuki** [4uiiurz1/pytorch-deform-conv-v2#30]
up up，想了很久不知道怎么解决，全部的问题如下：
Traceback (most recent call last):
  File "D:/Users/wwj/project/tph-yolov5-main/train.py", line 637, in <module>
    main(opt)
  File "D:/Users/wwj/project/tph-yolov5-main/train.py", line 534, in main
    train(opt.hyp, opt, device, callbacks)
  File "D:/Users/wwj/project/tph-yolov5-main/train.py", line 355, in train
    callbacks.run('on_train_batch_end', ni, model, imgs, targets, paths, plots, opt.sync_bn)
  File "D:\Users\wwj\project\tph-yolov5-main\utils\callbacks.py", line 76, in run
    logger['callback'](*args, **kwargs)
  File "D:\Users\wwj\project\tph-yolov5-main\utils\loggers\__init__.py", line 86, in on_train_batch_end
    self.tb.add_graph(torch.jit.trace(de_parallel(model), imgs[0:1], strict=False), [])
  File "D:\Users\wwj\Anaconda\envs\yolov5\lib\site-packages\torch\jit\_trace.py", line 750, in trace
    _module_class,
  File "D:\Users\wwj\Anaconda\envs\yolov5\lib\site-packages\torch\jit\_trace.py", line 942, in trace_module
    module = make_module(mod, _module_class, _compilation_unit)
  File "D:\Users\wwj\Anaconda\envs\yolov5\lib\site-packages\torch\jit\_trace.py", line 568, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "D:\Users\wwj\Anaconda\envs\yolov5\lib\site-packages\torch\jit\_trace.py", line 1068, in __init__
    submodule, TracedModule, _compilation_unit=None
  File "D:\Users\wwj\Anaconda\envs\yolov5\lib\site-packages\torch\jit\_trace.py", line 568, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "D:\Users\wwj\Anaconda\envs\yolov5\lib\site-packages\torch\jit\_trace.py", line 1068, in __init__
    submodule, TracedModule, _compilation_unit=None
  File "D:\Users\wwj\Anaconda\envs\yolov5\lib\site-packages\torch\jit\_trace.py", line 568, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "D:\Users\wwj\Anaconda\envs\yolov5\lib\site-packages\torch\jit\_trace.py", line 1068, in __init__
    submodule, TracedModule, _compilation_unit=None
  File "D:\Users\wwj\Anaconda\envs\yolov5\lib\site-packages\torch\jit\_trace.py", line 568, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "D:\Users\wwj\Anaconda\envs\yolov5\lib\site-packages\torch\jit\_trace.py", line 1061, in __init__
    + str(orig)

**Comment by minhtai048** [comment]
put `--no-trace` to your parsing code. It works for me! Hope it helps you too
